#Actions Template

name: Deploy Backend SAM

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install moto boto3
      run: pip install moto boto3
    - name: Try test
      run: python3 Lambda/test_counter.py
